-- Database: SBSENVIO

-- DROP DATABASE IF EXISTS "SBSENVIO";

CREATE DATABASE "SBSENVIO"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE "SBSENVIO" TO PUBLIC;

GRANT ALL ON DATABASE "SBSENVIO" TO postgres;